
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luiz Zimmermann
 */
public class Interface extends javax.swing.JFrame {
    
    

    static String hexToBin(String s) {
        if("0x".equals(s.substring(0, 2))){
            s = s.replace("0x", "");
    }
        String bin = new BigInteger(s, 16).toString(2);
        return String.format("%32s", bin).replace(" ", "0");
    }
    
    static String remove0x(String s) {
        return s = s.replaceAll("0x", "");
    }
    
    static String binToHex(String s){
        return null;
    }
    
    private static String leftShift_2bits(String val_dec) throws NumberFormatException {
        int decimal = Integer.parseInt(val_dec, 2) * 4; // Page Table Number * 4
        String valDeslocado = "0x00000" + Integer.toHexString(decimal); // Adicionando zeros para completar o nº
        return valDeslocado;
    }
    
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelmain = new javax.swing.JPanel();
        introducao1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new javax.swing.JToggleButton();
        introducao2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnok = new javax.swing.JToggleButton();
        introducao3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        VM = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pdbrn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btninictut = new javax.swing.JToggleButton();
        tutorial1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        VMhex = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        VMbin = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        offsetbin = new javax.swing.JLabel();
        PNbin = new javax.swing.JLabel();
        PTNbin = new javax.swing.JLabel();
        btntut2 = new javax.swing.JToggleButton();
        tutorial2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PTNbin2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PTNshift = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelmain.setBackground(new java.awt.Color(255, 255, 204));
        painelmain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Virtual Memory Andress");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tutorial");

        btn.setText("Iniciar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao1Layout = new javax.swing.GroupLayout(introducao1);
        introducao1.setLayout(introducao1Layout);
        introducao1Layout.setHorizontalGroup(
            introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel1)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btn))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        introducao1Layout.setVerticalGroup(
            introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(btn)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        painelmain.add(introducao1, "card2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tabela que nos usaremos como base para o nosso tutorial");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"}
            },
            new String [] {
                "              Adress", "             Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao2Layout = new javax.swing.GroupLayout(introducao2);
        introducao2.setLayout(introducao2Layout);
        introducao2Layout.setHorizontalGroup(
            introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(btnok)
                        .addGap(299, 299, 299))))
        );
        introducao2Layout.setVerticalGroup(
            introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnok)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        painelmain.add(introducao2, "card3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("VM:");

        VM.setText("jLabel5");

        jLabel5.setText("PDBR:");

        pdbrn.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Com os valores de VM e PDBR em mãos nos ja podemos ir em busca do endereço da memória fisica");

        btninictut.setText("Próximo");
        btninictut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninictutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao3Layout = new javax.swing.GroupLayout(introducao3);
        introducao3.setLayout(introducao3Layout);
        introducao3Layout.setHorizontalGroup(
            introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao3Layout.createSequentialGroup()
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(introducao3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(introducao3Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btninictut)
                            .addGroup(introducao3Layout.createSequentialGroup()
                                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VM)
                                    .addComponent(pdbrn))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        introducao3Layout.setVerticalGroup(
            introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(VM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pdbrn))
                .addGap(63, 63, 63)
                .addComponent(btninictut)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        painelmain.add(introducao3, "card4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Passo 1:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precisamos descobrir os valores para os campos PTN, PN e offset, onde:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("PTN: Numero da tabela de páginas onde esta a página de endereçoes que o processador quer.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PN: Numero da página onde esta o endereço fisico.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("offset: Valor para localizar o endereço fisico.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("VM:");

        VMhex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VMhex.setText("0x00000000");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Hex");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Para");

        VMbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VMbin.setText("00000000000000000000000000000000");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Bin");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Para isso nos precisamos converter o valor hexadecimal de VM para binario:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Depois pegar os 12 primeiros bits(da direita para esquerda) e atribuir ao offset.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Pegar os proximos 10 bits e atribuir ao PN.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("E por ultimo pegar os 10 bits restantes e atribuir ao PTN.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("offset:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("PN:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("PTN:");

        offsetbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        offsetbin.setText("jLabel23");

        PNbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PNbin.setText("jLabel24");

        PTNbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNbin.setText("jLabel25");

        btntut2.setText("Próximo");
        btntut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial1Layout = new javax.swing.GroupLayout(tutorial1);
        tutorial1.setLayout(tutorial1Layout);
        tutorial1Layout.setHorizontalGroup(
            tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addComponent(VMhex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VMbin)
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel17))))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(offsetbin))
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(PNbin)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PTNbin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntut2)
                .addGap(25, 25, 25))
        );
        tutorial1Layout.setVerticalGroup(
            tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(20, 20, 20)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(VMhex)
                    .addComponent(jLabel15)
                    .addComponent(VMbin))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(offsetbin))
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(PNbin))
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(4, 4, 4)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(PTNbin)
                    .addComponent(btntut2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelmain.add(tutorial1, "card5");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Passo 2:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Agora nos precisamos saber em qual tabela devemos buscar os endereços. Para isso, vamos fazer ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("alguns calculos.");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Devemos pegar o valor de PTN e multiplicar por quatro  porq bla bla bla:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Para multiplicar um numero em binario, basta somente adicionar zeros a direita dele, no caso, como queremos ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("multiplicar por 4, vamos adicionar 2 zeros a direita do valor de PTN.");

        PTNbin2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNbin2.setText("jLabel29");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("=");

        PTNshift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNshift.setText("jLabel31");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("* 4");

        javax.swing.GroupLayout tutorial2Layout = new javax.swing.GroupLayout(tutorial2);
        tutorial2.setLayout(tutorial2Layout);
        tutorial2Layout.setHorizontalGroup(
            tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tutorial2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial2Layout.createSequentialGroup()
                        .addComponent(PTNbin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PTNshift))
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tutorial2Layout.setVerticalGroup(
            tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTNbin2)
                    .addComponent(jLabel30)
                    .addComponent(PTNshift)
                    .addComponent(jLabel32))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        painelmain.add(tutorial2, "card6");

        getContentPane().add(painelmain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        int x = 0;
         for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            
            tabela.setValueAt(i.getKey(),x,0);
            tabela.setValueAt(i.getValue(),x,1);
            x++;   
        }
        
        painelmain.removeAll();
        painelmain.add(introducao2);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btnActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        
        VM.setText(vmAdress_hex);
        pdbrn.setText(pdbr);
        
        painelmain.removeAll();
        painelmain.add(introducao3);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btnokActionPerformed

    private void btninictutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninictutActionPerformed
        
        VMhex.setText(vmAdress_hex);
        VMbin.setText(vmAdress_bin);
        offsetbin.setText(offset);
        PNbin.setText(pagenumberUse);
        PTNbin.setText(pageTableNumber);
        painelmain.removeAll();
        painelmain.add(tutorial1);
        painelmain.repaint();
        painelmain.revalidate();
        
    }//GEN-LAST:event_btninictutActionPerformed

    private void btntut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut2ActionPerformed
        
        PTNbin2.setText(pageTableNumber);
        PTNshift.setText(pagenumberUse+"00");
        
        painelmain.removeAll();
        painelmain.add(tutorial2);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut2ActionPerformed

    static String pageTableNumber;
    static String pageNumber;
    static String pagenumberUse;
    static String offset;
    static HashMap<String, String> tabela_address_contents = new HashMap<>();
    static String vmAdress_hex;
    static String pdbr;
    static String vmAdress_bin;
    static String ptnDeslocado;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        //-----------------------------------------------------------------------------------------------//
        vmAdress_hex = "0x4580eb9c";
        pdbr = "0x001B3000";
        vmAdress_bin = hexToBin(vmAdress_hex);
        //System.out.println("VM Adress: " + vmAdress_bin);

        pageTableNumber = vmAdress_bin.substring(0, 10);
        pagenumberUse=pageTableNumber;
        pageNumber = vmAdress_bin.substring(10, 20);
        
        offset = vmAdress_bin.substring(20, 32);
        
        /*System.out.print("------ Endereços divididos -----\n");
        System.out.print("Page Table Number: " + pageTableNumber);
        System.out.print("\nPage Number: " + pageNumber);
        System.out.print("\nOffset: " + offset);
        System.out.print("\n\n");
        */
        ptnDeslocado = leftShift_2bits(pageTableNumber); 
        //System.out.println("\nPage Table Number * 4 = " + ptnDeslocado);
        
        int a = Integer.parseInt(remove0x(ptnDeslocado), 16);
        int b = Integer.parseInt(remove0x(pdbr), 16);
        int resultado = a + b;
        String adress1 = Integer.toHexString(resultado);
        adress1 = "0x00" + adress1; // Completa o resultado com dois zeros antes
        System.out.println("adress1:"+ adress1);
        
        
        tabela_address_contents.put("0x0001a038", "0x000b4045");
        tabela_address_contents.put("0x000b4b9c", "0x236b12c1");
        tabela_address_contents.put("0x000b91a0", "0x1b9d8fc5");
        tabela_address_contents.put("0x001b31cc", "0x003a9067");
        tabela_address_contents.put("0x001b3458", "0x0001a067");
        tabela_address_contents.put("0x003a9054", "0x000b9067");
        /* Ver o link https://wwww.w3schools.com/java/java_hashmap.asp
                      https://blog.alura.com.br/iterando-por-um-hashmap-em-java/
        */
        //System.out.println("\n\n");
        String conteudoMem = new String();
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (adress1.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        //System.out.println("conteudo:"+conteudoMem);
        
        HashMap<String, String> tabela_bits = new HashMap<>();
        tabela_bits.put("31-12", conteudoMem.substring(0, 7));
        tabela_bits.put("11-7", "0x" + hexToBin(conteudoMem).substring(20, 24));
        tabela_bits.put("6", hexToBin(conteudoMem).substring(25));
        tabela_bits.put("5", hexToBin(conteudoMem).substring(26));
        tabela_bits.put("4-3", hexToBin(conteudoMem).substring(27, 28));
        tabela_bits.put("2", hexToBin(conteudoMem).substring(29));
        tabela_bits.put("1", hexToBin(conteudoMem).substring(30));
        tabela_bits.put("0", hexToBin(conteudoMem).substring(31));
        
        
        String Contains1 = tabela_bits.get("31-12") + "000";
      
        //System.out.println("Contains1:"+Contains1);//
        
        pageNumber = leftShift_2bits(pageNumber);
        
        //System.out.println("PageNumber *4:"+pageNumber);//
        
        //pageNumber = pageNumber + "00";
        int pageNumberMult = Integer.parseInt(remove0x(pageNumber),16);
        //contains da tabela 1 mais 000
        int contains1Sum0 = Integer.parseInt(remove0x(Contains1),16);
        //System.out.println("contains:"+contains1Sum0);
        resultado = contains1Sum0 + pageNumberMult;
        String adress2 = Integer.toHexString(resultado);
        adress2 = "0x000"+ adress2;
        //System.out.println("adress2:"+adress2);
        //String pageNumberMultiplicado = Integer.toString(pageNumberMult,16);
        //int end = Integer.parseInt(Contains1, 16);
        //resultado = pageNumberMult + end;
 
        
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (adress1.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        //System.out.println("adress1:"+adress1);
        //System.out.println("\n\tPrimeiro conteúdo econtrado: " + conteudoMem);
        
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (adress2.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
       // System.out.println("adress2:"+adress2);
       // System.out.println("\n\tSegundo conteúdo econtrado: " + conteudoMem);
        
        
//------------------------------------------------------------------------------------------//
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PNbin;
    private javax.swing.JLabel PTNbin;
    private javax.swing.JLabel PTNbin2;
    private javax.swing.JLabel PTNshift;
    private javax.swing.JLabel VM;
    private javax.swing.JLabel VMbin;
    private javax.swing.JLabel VMhex;
    private javax.swing.JToggleButton btn;
    private javax.swing.JToggleButton btninictut;
    private javax.swing.JToggleButton btnok;
    private javax.swing.JToggleButton btntut2;
    private javax.swing.JPanel introducao1;
    private javax.swing.JPanel introducao2;
    private javax.swing.JPanel introducao3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel offsetbin;
    private javax.swing.JPanel painelmain;
    private javax.swing.JLabel pdbrn;
    private javax.swing.JTable tabela;
    private javax.swing.JPanel tutorial1;
    private javax.swing.JPanel tutorial2;
    // End of variables declaration//GEN-END:variables
}
