
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luiz Zimmermann
 */
public class Interface extends javax.swing.JFrame {
    
    

    static String hexToBin(String s) {
        if("0x".equals(s.substring(0, 2))){
            s = s.replace("0x", "");
    }
        String bin = new BigInteger(s, 16).toString(2);
        return String.format("%32s", bin).replace(" ", "0");
    }
    
    static String remove0x(String s) {
        return s = s.replaceAll("0x", "");
    }
    
    static String binToHex(String s){
        return null;
    }
    
    static String completaZeros(String valor){ // Função para completar os zeros a esquerda do numero
        switch(valor.length()){
            case 1: return "0000000" + valor; // 7 zeros
            case 2: return "000000" + valor; // 6 zeros
            case 3: return "00000" + valor; // 5 zeros
            case 4: return "0000" + valor; // 4 zeros
            case 5: return "000" + valor; // 3 zeros
            case 6: return "00" + valor; // 2 zeros
            case 7: return "0" + valor; // 1 zero
        }
        return valor;
    }
    
    private static String leftShift_2bits(String val_dec) throws NumberFormatException {
        int decimal = Integer.parseInt(val_dec, 2) * 4; // Page Table Number * 4
        String valDeslocado = "0x00000" + Integer.toHexString(decimal); // Adicionando zeros para completar o nº
        return valDeslocado;
    }
    
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelmain = new javax.swing.JPanel();
        introducao1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn = new javax.swing.JToggleButton();
        introducao2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnok = new javax.swing.JToggleButton();
        introducao3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        VM = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pdbrn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btninictut = new javax.swing.JToggleButton();
        tutorial1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        VMhex = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        VMbin = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        offsetbin = new javax.swing.JLabel();
        PNbin = new javax.swing.JLabel();
        PTNbin = new javax.swing.JLabel();
        btntut2 = new javax.swing.JToggleButton();
        tutorial2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PTNbin2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PTNshift = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        PTNshifthex = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pdbrsum = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        ptnsum = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        adressbin = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        pdbrsumh = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        ptnsumh = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        adresshex = new javax.swing.JLabel();
        btntut3 = new javax.swing.JToggleButton();
        tutorial3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        adress1t = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        conteudo1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela3 = new javax.swing.JTable();
        conteudo1bin = new javax.swing.JLabel();
        btntut4 = new javax.swing.JToggleButton();
        tutorial4 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        pnshift = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        conteudosum = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        pnsum = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        adress2sum = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        btntut5 = new javax.swing.JToggleButton();
        tutorial5 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabela4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabela5 = new javax.swing.JTable();
        jLabel61 = new javax.swing.JLabel();
        adress2cnt = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        conteudo2 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        conteudo2bin = new javax.swing.JLabel();
        btntut6 = new javax.swing.JToggleButton();
        tutorial6 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        conteudo2sum = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        offsetsum = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        adress3ct = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabela6 = new javax.swing.JTable();
        jLabel69 = new javax.swing.JLabel();
        enderecofis = new javax.swing.JLabel();
        btnfin = new javax.swing.JButton();
        pfinal = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelmain.setBackground(new java.awt.Color(255, 255, 204));
        painelmain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Virtual Memory Andress");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tutorial");

        btn.setText("Iniciar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao1Layout = new javax.swing.GroupLayout(introducao1);
        introducao1.setLayout(introducao1Layout);
        introducao1Layout.setHorizontalGroup(
            introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel1)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btn))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        introducao1Layout.setVerticalGroup(
            introducao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(btn)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        painelmain.add(introducao1, "card2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tabela que nos usaremos como base para o nosso tutorial");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"}
            },
            new String [] {
                "              Adress", "             Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao2Layout = new javax.swing.GroupLayout(introducao2);
        introducao2.setLayout(introducao2Layout);
        introducao2Layout.setHorizontalGroup(
            introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introducao2Layout.createSequentialGroup()
                        .addComponent(btnok)
                        .addGap(310, 310, 310))))
        );
        introducao2Layout.setVerticalGroup(
            introducao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnok)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        painelmain.add(introducao2, "card3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("VM:");

        VM.setText("0x00000000");

        jLabel5.setText("PDBR:");

        pdbrn.setText("0x00000000");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Com os valores de VM e PDBR em mãos nos ja podemos ir em busca do endereço da memória fisica");

        btninictut.setText("Próximo");
        btninictut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninictutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout introducao3Layout = new javax.swing.GroupLayout(introducao3);
        introducao3.setLayout(introducao3Layout);
        introducao3Layout.setHorizontalGroup(
            introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao3Layout.createSequentialGroup()
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(introducao3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6))
                    .addGroup(introducao3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VM)
                            .addComponent(pdbrn)))
                    .addGroup(introducao3Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btninictut)))
                .addContainerGap())
        );
        introducao3Layout.setVerticalGroup(
            introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introducao3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(VM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(introducao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pdbrn))
                .addGap(50, 50, 50)
                .addComponent(btninictut)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        painelmain.add(introducao3, "card4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Passo 1:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precisamos descobrir os valores para os campos PTN, PN e offset, onde:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("PTN: Numero da tabela de páginas onde esta a página de endereçoes que o processador quer.");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("PN: Numero da página onde esta o endereço fisico.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("offset: Valor para localizar o endereço fisico.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("VM:");

        VMhex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VMhex.setText("0x00000000");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Hex");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Para");

        VMbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VMbin.setText("00000000000000000000000000000000");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Bin");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Para isso nos precisamos converter o valor hexadecimal de VM para binario:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Depois pegar os 12 primeiros bits(da direita para esquerda) e atribuir ao offset.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Pegar os proximos 10 bits e atribuir ao PN.");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("E por ultimo pegar os 10 bits restantes e atribuir ao PTN.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("offset:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("PN:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("PTN:");

        offsetbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        offsetbin.setText("jLabel23");

        PNbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PNbin.setText("jLabel24");

        PTNbin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNbin.setText("jLabel25");

        btntut2.setText("Próximo");
        btntut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial1Layout = new javax.swing.GroupLayout(tutorial1);
        tutorial1.setLayout(tutorial1Layout);
        tutorial1Layout.setHorizontalGroup(
            tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PTNbin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial1Layout.createSequentialGroup()
                        .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tutorial1Layout.createSequentialGroup()
                                        .addComponent(VMhex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(tutorial1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel14)))
                                .addGap(18, 18, 18)
                                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VMbin)
                                    .addGroup(tutorial1Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel17))))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offsetbin))
                            .addGroup(tutorial1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(PNbin)))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorial1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntut2)))
                .addContainerGap())
        );
        tutorial1Layout.setVerticalGroup(
            tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(20, 20, 20)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(VMhex)
                    .addComponent(jLabel15)
                    .addComponent(VMbin))
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(offsetbin))
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(PNbin))
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addGap(5, 5, 5)
                .addGroup(tutorial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(PTNbin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btntut2)
                .addContainerGap())
        );

        painelmain.add(tutorial1, "card5");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Passo 2:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Agora nos precisamos saber em qual tabela devemos buscar os endereços. Para isso, vamos fazer ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("alguns calculos.");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Devemos pegar o valor de PTN e multiplicar por quatro  porq bla bla bla:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Para multiplicar um numero em binario, basta somente adicionar zeros a direita dele, no caso, como queremos ");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("multiplicar por 4, vamos adicionar 2 zeros a direita do valor de PTN.");

        PTNbin2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNbin2.setText("jLabel29");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("=");

        PTNshift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNshift.setText("000000000000");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("* 4");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Bin");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("para");

        PTNshifthex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PTNshifthex.setText("0x00000000");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Hex");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Agora devemos somar o valor de PDBR com o PTN deslocado para encontrar o endereço inicial da tabela.");

        pdbrsum.setText("jLabel35");

        jLabel36.setText("+");

        ptnsum.setText("jLabel37");

        jLabel35.setText("=");

        adressbin.setText("jLabel37");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Bin");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Hex");

        pdbrsumh.setText("jLabel39");

        jLabel40.setText("+");

        ptnsumh.setText("jLabel41");

        jLabel39.setText("=");

        adresshex.setText("jLabel41");

        btntut3.setText("Próximo");
        btntut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial2Layout = new javax.swing.GroupLayout(tutorial2);
        tutorial2.setLayout(tutorial2Layout);
        tutorial2Layout.setHorizontalGroup(
            tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial2Layout.createSequentialGroup()
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tutorial2Layout.createSequentialGroup()
                        .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addGroup(tutorial2Layout.createSequentialGroup()
                                        .addComponent(PTNbin2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tutorial2Layout.createSequentialGroup()
                                                .addComponent(PTNshift)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel31)
                                                .addGap(28, 28, 28)
                                                .addComponent(PTNshifthex))
                                            .addGroup(tutorial2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel29)
                                                .addGap(140, 140, 140)
                                                .addComponent(jLabel34))))
                                    .addGroup(tutorial2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tutorial2Layout.createSequentialGroup()
                                                .addComponent(pdbrsum)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ptnsum)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel35)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(adressbin))
                                            .addGroup(tutorial2Layout.createSequentialGroup()
                                                .addComponent(pdbrsumh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel40)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ptnsumh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel39)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adresshex))))
                                    .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btntut3)
                                        .addComponent(jLabel33))))
                            .addGroup(tutorial2Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel37))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tutorial2Layout.setVerticalGroup(
            tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addGap(0, 0, 0)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel34))
                .addGap(5, 5, 5)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTNbin2)
                    .addComponent(jLabel30)
                    .addComponent(PTNshift)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31)
                    .addComponent(PTNshifthex))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(20, 20, 20)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdbrsum)
                    .addComponent(jLabel36)
                    .addComponent(ptnsum)
                    .addComponent(jLabel35)
                    .addComponent(adressbin))
                .addGap(27, 27, 27)
                .addComponent(jLabel38)
                .addGap(2, 2, 2)
                .addGroup(tutorial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdbrsumh)
                    .addComponent(jLabel40)
                    .addComponent(ptnsumh)
                    .addComponent(jLabel39)
                    .addComponent(adresshex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btntut3)
                .addContainerGap())
        );

        painelmain.add(tutorial2, "card6");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Passo 3:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Agora que emcontramos o endereço, devemos olhar na tabela para ver oque ele contém.");

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"}
            },
            new String [] {
                "              Adress", "             Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela2);
        if (tabela2.getColumnModel().getColumnCount() > 0) {
            tabela2.getColumnModel().getColumn(0).setResizable(false);
            tabela2.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("O conteudo do endereço");

        adress1t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress1t.setText("jLabel44");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("contém");

        conteudo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conteudo1.setText("jLabel45");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Decodificando nos temos:");

        tabela3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"}
            },
            new String [] {
                "Bit(s)", "Contains"
            }
        ));
        jScrollPane3.setViewportView(tabela3);

        conteudo1bin.setText("jLabel46");

        btntut4.setText("Próximo");
        btntut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial3Layout = new javax.swing.GroupLayout(tutorial3);
        tutorial3.setLayout(tutorial3Layout);
        tutorial3Layout.setHorizontalGroup(
            tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial3Layout.createSequentialGroup()
                        .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial3Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42))
                            .addGroup(tutorial3Layout.createSequentialGroup()
                                .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tutorial3Layout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel45))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adress1t)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conteudo1))
                            .addGroup(tutorial3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(conteudo1bin)))
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(tutorial3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntut4)))
                .addContainerGap())
        );
        tutorial3Layout.setVerticalGroup(
            tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel45))
                            .addGroup(tutorial3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel43)
                                .addComponent(adress1t)
                                .addComponent(jLabel44)
                                .addComponent(conteudo1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conteudo1bin)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorial3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntut4)
                        .addContainerGap())))
        );

        painelmain.add(tutorial3, "card7");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel46.setText("Passo 4:");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Agora, para encontrar qual a paginda de endereços, devemos fazer outro calculo.");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Somar o conteudo dos bits 31-12 da tabela anterior adicionando os 0 nescessarios(a direita) ");

        pn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pn.setText("jLabel49");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel50.setText("*4");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("=");

        pnshift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnshift.setText("0x00000000");

        jLabel53.setText("PN");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("para completar o numero e somar com o PN multiplicado por 4.");

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel52.setText("Conteudo");

        conteudosum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conteudosum.setText("0x00000000");

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel55.setText("+");

        pnsum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnsum.setText("0x00000000");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel57.setText("=");

        adress2sum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress2sum.setText("0x00000000");

        jLabel54.setText("PNshift");

        jLabel56.setText("Endereço");

        jLabel58.setText("PN shift");

        btntut5.setText("Próximo");
        btntut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial4Layout = new javax.swing.GroupLayout(tutorial4);
        tutorial4.setLayout(tutorial4Layout);
        tutorial4Layout.setHorizontalGroup(
            tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial4Layout.createSequentialGroup()
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial4Layout.createSequentialGroup()
                        .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial4Layout.createSequentialGroup()
                                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(conteudosum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnsum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel54)
                                        .addGap(27, 27, 27)))
                                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addComponent(jLabel57)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(adress2sum))
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel56))))
                            .addGroup(tutorial4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel47))
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel53)
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabel58))
                                    .addGroup(tutorial4Layout.createSequentialGroup()
                                        .addComponent(pn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel50)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel51)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnshift))
                                    .addComponent(jLabel49))))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorial4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btntut5)))
                .addContainerGap())
        );
        tutorial4Layout.setVerticalGroup(
            tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addGap(19, 19, 19)
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pn)
                    .addComponent(jLabel50)
                    .addComponent(jLabel51)
                    .addComponent(pnshift))
                .addGap(41, 41, 41)
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel54)
                    .addComponent(jLabel56))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conteudosum)
                    .addComponent(jLabel55)
                    .addComponent(pnsum)
                    .addComponent(jLabel57)
                    .addComponent(adress2sum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(btntut5)
                .addContainerGap())
        );

        painelmain.add(tutorial4, "card8");

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59.setText("Passo 5:");

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60.setText("Temos que ollhar na tabela novamente e pegar o conteúdo que está contido no endereço.");

        tabela4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"},
                {"n", "n"}
            },
            new String [] {
                "Bit(s)", "Contains"
            }
        ));
        jScrollPane4.setViewportView(tabela4);

        tabela5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"}
            },
            new String [] {
                "              Adress", "             Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabela5);
        if (tabela5.getColumnModel().getColumnCount() > 0) {
            tabela5.getColumnModel().getColumn(0).setResizable(false);
            tabela5.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel61.setText("O conteudo do endereço");

        adress2cnt.setText("jLabel62");

        jLabel63.setText("cotém");

        conteudo2.setText("jLabel64");

        jLabel62.setText("Decodificando temos:");

        conteudo2bin.setText("jLabel64");

        btntut6.setText("Próximo");
        btntut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntut6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial5Layout = new javax.swing.GroupLayout(tutorial5);
        tutorial5.setLayout(tutorial5Layout);
        tutorial5Layout.setHorizontalGroup(
            tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial5Layout.createSequentialGroup()
                        .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorial5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(conteudo2bin))
                            .addGroup(tutorial5Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adress2cnt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conteudo2))
                            .addComponent(jLabel62)
                            .addGroup(tutorial5Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel60)))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(tutorial5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntut6)))
                .addContainerGap())
        );
        tutorial5Layout.setVerticalGroup(
            tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60))
                .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tutorial5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel61)
                                .addComponent(adress2cnt)
                                .addComponent(jLabel63)
                                .addComponent(conteudo2)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(conteudo2bin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorial5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntut6)
                        .addContainerGap())))
        );

        painelmain.add(tutorial5, "card9");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64.setText("Passo 6:");

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel65.setText("Agora devemos fazer um último calculo(finalmente). Temos que somar o conteúdo dos bits 31-12 ");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel66.setText("que obtivemos no passo anterior, e somar com o valor de offset.");

        conteudo2sum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conteudo2sum.setText("0x00000000");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel68.setText("+");

        offsetsum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        offsetsum.setText("0x00000000");

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel70.setText("=");

        adress3ct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adress3ct.setText("0x00000000");

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel72.setText("Conteudo");

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel73.setText("offset");

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel74.setText("Endereço");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel67.setText("Olhando na tabela um última vez para obtermos finalmente o endereço físico.");

        tabela6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"},
                {"nulo", "nulo"}
            },
            new String [] {
                "              Adress", "             Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tabela6);
        if (tabela6.getColumnModel().getColumnCount() > 0) {
            tabela6.getColumnModel().getColumn(0).setResizable(false);
            tabela6.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel69.setText("E finalmente temos o nosso endereço fisico:");

        enderecofis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enderecofis.setText("jLabel71");

        btnfin.setText("Próximo");
        btnfin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tutorial6Layout = new javax.swing.GroupLayout(tutorial6);
        tutorial6.setLayout(tutorial6Layout);
        tutorial6Layout.setHorizontalGroup(
            tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tutorial6Layout.createSequentialGroup()
                        .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(conteudo2sum)
                            .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel72)
                                .addComponent(jLabel64)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66)
                            .addComponent(jLabel65)
                            .addGroup(tutorial6Layout.createSequentialGroup()
                                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tutorial6Layout.createSequentialGroup()
                                        .addComponent(jLabel68)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(offsetsum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel70))
                                    .addGroup(tutorial6Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel73)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adress3ct)
                                    .addGroup(tutorial6Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel74))))))
                    .addComponent(jLabel67)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tutorial6Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enderecofis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorial6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnfin)
                .addContainerGap())
        );
        tutorial6Layout.setVerticalGroup(
            tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorial6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jLabel65))
                .addGap(0, 0, 0)
                .addComponent(jLabel66)
                .addGap(48, 48, 48)
                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel73)
                    .addComponent(jLabel74))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conteudo2sum)
                    .addComponent(jLabel68)
                    .addComponent(offsetsum)
                    .addComponent(jLabel70)
                    .addComponent(adress3ct))
                .addGap(32, 32, 32)
                .addComponent(jLabel67)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tutorial6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(enderecofis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnfin)
                .addContainerGap())
        );

        painelmain.add(tutorial6, "card10");

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel71.setText("Espero que tenham entendido ");

        javax.swing.GroupLayout pfinalLayout = new javax.swing.GroupLayout(pfinal);
        pfinal.setLayout(pfinalLayout);
        pfinalLayout.setHorizontalGroup(
            pfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pfinalLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel71)
                .addGap(163, 163, 163))
        );
        pfinalLayout.setVerticalGroup(
            pfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfinalLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel71)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        painelmain.add(pfinal, "card11");

        getContentPane().add(painelmain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        int x = 0;
         for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            
            tabela.setValueAt(i.getKey(),x,0);
            tabela.setValueAt(i.getValue(),x,1);
            x++;   
        }
        
        painelmain.removeAll();
        painelmain.add(introducao2);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btnActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        
        VM.setText(vmAdress_hex);
        pdbrn.setText(pdbr);
        
        painelmain.removeAll();
        painelmain.add(introducao3);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btnokActionPerformed

    private void btninictutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninictutActionPerformed
        
        VMhex.setText(vmAdress_hex);
        VMbin.setText(vmAdress_bin);
        offsetbin.setText(offset);
        PNbin.setText(pagenumberUse);
        PTNbin.setText(pageTableNumber);
        painelmain.removeAll();
        painelmain.add(tutorial1);
        painelmain.repaint();
        painelmain.revalidate();
        
    }//GEN-LAST:event_btninictutActionPerformed

    private void btntut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut2ActionPerformed
        
        PTNbin2.setText(pageTableNumber);
        PTNshift.setText(pagenumberUse+"00");
        PTNshifthex.setText(ptnDeslocado);
        ptnsum.setText(pagenumberUse+"00");
        pdbrsum.setText(pdbrUse);
        adressbin.setText(adress1Bin);
        pdbrsumh.setText(pdbr);
        ptnsumh.setText(ptnDeslocado);
        adresshex.setText(adress1);
        
        painelmain.removeAll();
        painelmain.add(tutorial2);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut2ActionPerformed

    private void btntut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut3ActionPerformed
        
        int x =0, y=7;
        String conteudoMem="";
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            
            tabela2.setValueAt(i.getKey(),x,0);
            tabela2.setValueAt(i.getValue(),x,1);
            x++;   
            
            if (adress1.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        
         for (Map.Entry<String, String> i : tabela1_bits.entrySet()){
            
            tabela3.setValueAt(i.getKey(),y,0);
            tabela3.setValueAt(i.getValue(),y,1);
            y--;   

        }

         adress1t.setText(adress1);
         conteudo1.setText(conteudoMem);
         conteudo1bin.setText(conteudo1Bin);
        
        painelmain.removeAll();
        painelmain.add(tutorial3);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut3ActionPerformed

    private void btntut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut4ActionPerformed
        pn.setText(pageNumberUse);
        pnshift.setText(pageNumber);
        pnsum.setText(pageNumber);
        conteudosum.setText(conteudo31_12);
        adress2sum.setText(adress2);
        painelmain.removeAll();
        painelmain.add(tutorial4);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut4ActionPerformed

    private void btntut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut5ActionPerformed
       int x =0, y=7;
        String conteudoMem="";
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            
            tabela5.setValueAt(i.getKey(),x,0);
            tabela5.setValueAt(i.getValue(),x,1);
            x++;   
            
            if (adress2.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        
         for (Map.Entry<String, String> i : tabela2_bits.entrySet()){
            
            tabela4.setValueAt(i.getKey(),y,0);
            tabela4.setValueAt(i.getValue(),y,1);
            y--;   

        }

         adress2cnt.setText(adress2);
         conteudo2.setText(conteudoMem);
         conteudo2bin.setText(conteudo2Bin);
        
        painelmain.removeAll();
        painelmain.add(tutorial5);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut5ActionPerformed

    private void btntut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntut6ActionPerformed
        int x=0;
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            
            tabela6.setValueAt(i.getKey(),x,0);
            tabela6.setValueAt(i.getValue(),x,1);
            x++;   
   
        }
        
        conteudo2sum.setText(segundo_conteudo31_12);
        offsetsum.setText(offseth);
        adress3ct.setText(address3);
        enderecofis.setText(adressphy);
        
        painelmain.removeAll();
        painelmain.add(tutorial6);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btntut6ActionPerformed

    private void btnfinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinActionPerformed
        painelmain.removeAll();
        painelmain.add(pfinal);
        painelmain.repaint();
        painelmain.revalidate();
    }//GEN-LAST:event_btnfinActionPerformed

    static String pageTableNumber;
    static String pageNumber;
    static String pagenumberUse;
    static String offset;
    static String offseth;
    static HashMap<String, String> tabela_address_contents = new HashMap<>();
    static String vmAdress_hex;
    static String pdbr;
    static String pdbrUse;
    static String vmAdress_bin;
    static String ptnDeslocado;
    static String adress1;
    static String adress1Bin;
    static HashMap<String, String> tabela1_bits = new HashMap<>();
    static HashMap<String, String> tabela2_bits = new HashMap<>();
    static String conteudo1Bin;
    static String conteudo2Bin;
    static String conteudo31_12;
    static String segundo_conteudo31_12;
    static String pageNumberUse;
    static String adress2;
    static String address3;
    static String adressphy;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        //-----------------------------------------------------------------------------------------------//
        vmAdress_hex = "0x4580eb9c";
        pdbr = "0x001B3000";
        pdbrUse = hexToBin(pdbr);
        vmAdress_bin = hexToBin(vmAdress_hex);

        pageTableNumber = vmAdress_bin.substring(0, 10);
        pagenumberUse=pageTableNumber;
        pageNumber = vmAdress_bin.substring(10, 20);
        int pndc = Integer.parseInt(pageNumber,2);
        pageNumberUse = Integer.toString(pndc,16);
        pageNumberUse = "0x" + completaZeros(pageNumberUse);
                

        offset = vmAdress_bin.substring(20, 32);
        int offsetc = Integer.parseInt(offset,2);
        offseth = Integer.toString(offsetc,16);
        offseth = "0x" + completaZeros(offseth);
       
        ptnDeslocado = leftShift_2bits(pageTableNumber); 
        int a = Integer.parseInt(remove0x(ptnDeslocado), 16);
        int b = Integer.parseInt(remove0x(pdbr), 16);
        int resultado = a + b;
       
        adress1 = Integer.toHexString(resultado);
        adress1 = "0x" + completaZeros(adress1); // Completa o resultado com dois zeros antes
        adress1Bin = hexToBin(adress1);
        System.out.println("adress1:"+ adress1);
        
        
        tabela_address_contents.put("0x0001a038", "0x000b4045");
        tabela_address_contents.put("0x000b4b9c", "0x236b12c1");
        tabela_address_contents.put("0x000b91a0", "0x1b9d8fc5");
        tabela_address_contents.put("0x001b31cc", "0x003a9067");
        tabela_address_contents.put("0x001b3458", "0x0001a067");
        tabela_address_contents.put("0x003a9054", "0x000b9067");
        /* Ver o link https://wwww.w3schools.com/java/java_hashmap.asp
                      https://blog.alura.com.br/iterando-por-um-hashmap-em-java/
        */
      
        String conteudoMem = new String();
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (adress1.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        conteudo1Bin = hexToBin(conteudoMem);
        
        tabela1_bits.put("31-12", conteudoMem.substring(0, 7));
        tabela1_bits.put("11-7", "0x" + hexToBin(conteudoMem).substring(20, 24));
        tabela1_bits.put("6", hexToBin(conteudoMem).substring(25, 26));
        tabela1_bits.put("5", hexToBin(conteudoMem).substring(26, 27));
        tabela1_bits.put("4-3", hexToBin(conteudoMem).substring(27, 29));
        tabela1_bits.put("2", hexToBin(conteudoMem).substring(29, 30));
        tabela1_bits.put("1", hexToBin(conteudoMem).substring(30, 31));
        tabela1_bits.put("0", hexToBin(conteudoMem).substring(31));
        
        conteudo31_12 = tabela1_bits.get("31-12") + "000"; // Completando (31-12) com zeros
        System.out.println("Conteudo (31-12): " + conteudo31_12); // Conteúdo do primeiro endereço
        pageNumber = leftShift_2bits(pageNumber); // Multiplica o PN por 4
        System.out.println("PageNumber * 4: " + pageNumber); // Imprime o PN Multiplicado
        
        int pageNumberMult = Integer.parseInt(remove0x(pageNumber),16); // Converte PN para decimal 
        int contains1Sum0 = Integer.parseInt(remove0x(conteudo31_12),16); // Converte os primeiros 10 bits do primeiro conteúdo para decimal
        resultado = contains1Sum0 + pageNumberMult; // Soma os dois decimais convertidos
        adress2 = Integer.toHexString(resultado); // Converte o resultado para String Hexadecimal
        adress2 = "0x"+ completaZeros(adress2); 
        System.out.println("Adress2: " + adress2);

        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (adress2.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        System.out.println("cont2:"+conteudoMem);
        conteudo2Bin = hexToBin(conteudoMem);
       //---------------------------------------------
        tabela2_bits.put("31-12", conteudoMem.substring(0, 7));
        tabela2_bits.put("11-7", "0x" + hexToBin(conteudoMem).substring(20, 24));
        tabela2_bits.put("6", hexToBin(conteudoMem).substring(25, 26));
        tabela2_bits.put("5", hexToBin(conteudoMem).substring(26, 27));
        tabela2_bits.put("4-3", hexToBin(conteudoMem).substring(27, 29));
        tabela2_bits.put("2", hexToBin(conteudoMem).substring(29, 30));
        tabela2_bits.put("1", hexToBin(conteudoMem).substring(30, 31));
        tabela2_bits.put("0", hexToBin(conteudoMem).substring(31));
       
        segundo_conteudo31_12 = tabela2_bits.get("31-12") + "000"; // Completando (31-12) com zeros
        System.out.println("2º Conteudo 31-12: " + segundo_conteudo31_12); // Conteúdo do primeiro endereço
        
        int offset_int = Integer.parseInt(offset, 2); // Converte PN para decimal 
        int segundo_conteudo31_12_int = Integer.parseInt(remove0x(segundo_conteudo31_12),16); // Converte os primeiros 10 bits do primeiro conteúdo para decimal
        resultado = offset_int + segundo_conteudo31_12_int; // Soma os dois decimais convertidos
        address3 = Integer.toHexString(resultado); // Converte o resultado para String Hexadecimal
        address3 = "0x" + completaZeros(address3);
        
        System.out.println("\n3º Endereço: " + address3);
        
        for (Map.Entry<String, String> i : tabela_address_contents.entrySet()){
            if (address3.equals(i.getKey())){
                conteudoMem = i.getValue();
            }
        }
        adressphy = conteudoMem;
        System.out.println("3º conteudo (end. fisico): " + conteudoMem);
         
//------------------------------------------------------------------------------------------//
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PNbin;
    private javax.swing.JLabel PTNbin;
    private javax.swing.JLabel PTNbin2;
    private javax.swing.JLabel PTNshift;
    private javax.swing.JLabel PTNshifthex;
    private javax.swing.JLabel VM;
    private javax.swing.JLabel VMbin;
    private javax.swing.JLabel VMhex;
    private javax.swing.JLabel adress1t;
    private javax.swing.JLabel adress2cnt;
    private javax.swing.JLabel adress2sum;
    private javax.swing.JLabel adress3ct;
    private javax.swing.JLabel adressbin;
    private javax.swing.JLabel adresshex;
    private javax.swing.JToggleButton btn;
    private javax.swing.JButton btnfin;
    private javax.swing.JToggleButton btninictut;
    private javax.swing.JToggleButton btnok;
    private javax.swing.JToggleButton btntut2;
    private javax.swing.JToggleButton btntut3;
    private javax.swing.JToggleButton btntut4;
    private javax.swing.JToggleButton btntut5;
    private javax.swing.JToggleButton btntut6;
    private javax.swing.JLabel conteudo1;
    private javax.swing.JLabel conteudo1bin;
    private javax.swing.JLabel conteudo2;
    private javax.swing.JLabel conteudo2bin;
    private javax.swing.JLabel conteudo2sum;
    private javax.swing.JLabel conteudosum;
    private javax.swing.JLabel enderecofis;
    private javax.swing.JPanel introducao1;
    private javax.swing.JPanel introducao2;
    private javax.swing.JPanel introducao3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel offsetbin;
    private javax.swing.JLabel offsetsum;
    private javax.swing.JPanel painelmain;
    private javax.swing.JLabel pdbrn;
    private javax.swing.JLabel pdbrsum;
    private javax.swing.JLabel pdbrsumh;
    private javax.swing.JPanel pfinal;
    private javax.swing.JLabel pn;
    private javax.swing.JLabel pnshift;
    private javax.swing.JLabel pnsum;
    private javax.swing.JLabel ptnsum;
    private javax.swing.JLabel ptnsumh;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela2;
    private javax.swing.JTable tabela3;
    private javax.swing.JTable tabela4;
    private javax.swing.JTable tabela5;
    private javax.swing.JTable tabela6;
    private javax.swing.JPanel tutorial1;
    private javax.swing.JPanel tutorial2;
    private javax.swing.JPanel tutorial3;
    private javax.swing.JPanel tutorial4;
    private javax.swing.JPanel tutorial5;
    private javax.swing.JPanel tutorial6;
    // End of variables declaration//GEN-END:variables
}
